### ISSUE TITLE
MalformatedJsonException

### ISSUE THREAD

**Issue by catalin-florescu** [Computop/Computop-Android-Example#2]
Checkout cause `MalformatedJsonException`, should use `new Gson()..setLenient(true)` in return method ` return (PaymentMethodListResponse)(new Gson()).fromJson(...` from the SDK.

**Comment by ShkurtiA** [comment]
Do you get that exception or you are suggesting a solution to avoid that?

**Comment by catalin-florescu** [comment]
Both of them.

**Comment by ShkurtiA** [comment]
Can you share some more details how you use the library and the logs that you get from it?
